-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Chance"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    level smallint NOT NULL DEFAULT 0,
    success_value smallint NOT NULL,
    item_id bigint NOT NULL,
    CONSTRAINT "Chance_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Item"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    type smallint NOT NULL DEFAULT 0,
    save_enchant_level smallint NOT NULL,
    CONSTRAINT "Item_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ItemType"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "ItemType_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Tries"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    level smallint NOT NULL,
    item_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT "Tries_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Chance"
    ADD CONSTRAINT fk_chance_item FOREIGN KEY (item_id)
    REFERENCES public."Item" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Item"
    ADD CONSTRAINT fk_item_item_type FOREIGN KEY (type)
    REFERENCES public."ItemType" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Tries"
    ADD CONSTRAINT fk_tries_item FOREIGN KEY (item_id)
    REFERENCES public."Item" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Tries"
    ADD CONSTRAINT fk_tries_user FOREIGN KEY (user_id)
    REFERENCES public."User" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;